### ISSUE TITLE
Precision

### ISSUE THREAD

**Issue by zjjAmber** [Mrneet/Efficient_LocationRobust_TDOALoc_MPR#1]
How much time delay precision can be achieved by this algorithm?Thanks.

**Comment by Mrneet** [comment]
This is a localization method using TDOA rather than time delay estimation.

**Comment by zjjAmber** [comment]
I know, but you must estimate the time delay when using TDOA location. I mean how accurate the time delay estimated by this algorithm is, such as milliseconds or microseconds.

**Comment by Mrneet** [comment]
I am sorry that we didn't consider how to estimate TDOA in this algorithm. We just consider how to locate a source when TDOAs have been estimated. Regarding the required TDOA accuracy, it depends on the baseline or the size of your scenario.

**Comment by zjjAmber** [comment]
I know, but you must estimate the time delay when using TDOA location. I mean how accurate the time delay estimated by this algorithm is, such as milliseconds or microseconds.

**Comment by zjjAmber** [comment]
OK, I see. Thank you for your answer.

**Comment by Mrneet** [comment]
You may have a look at the paper for more details.
[Solution and Analysis of TDOA Localization of a Near or Distant Source in Closed Form](https://ieeexplore.ieee.org/document/8521706/)

**Comment by zjjAmber** [comment]
ok, thank you.
